"""add_embeddings

Revision ID: 0198e3ad2d51
Revises: 7d10a46c8880
Create Date: 2025-03-11 12:45:17.392734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision: str = '0198e3ad2d51'
down_revision: Union[str, None] = '7d10a46c8880'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('embeddings', sa.JSON(), nullable=True))
    op.alter_column('image', 'mimetype',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('image', 'mimetype',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('image', 'embeddings')
    # ### end Alembic commands ###
