"""add_preview

Revision ID: a88a683391a9
Revises: 0198e3ad2d51
Create Date: 2025-03-13 03:16:46.750851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added


# revision identifiers, used by Alembic.
revision: str = 'a88a683391a9'
down_revision: Union[str, None] = '0198e3ad2d51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('filepath_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'filepath_preview')
    # ### end Alembic commands ###
